# --- Certificate Authority ---

resource "tls_private_key" "ca" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "tls_self_signed_cert" "ca" {
  private_key_pem = tls_private_key.ca.private_key_pem

  subject {
    common_name  = var.ca_common_name
    organization = "Checkout.com"
  }

  validity_period_hours = var.ca_validity_hours
  is_ca_certificate     = true

  allowed_uses = [
    "cert_signing",
    "crl_signing",
  ]
}

# --- Client Certificate ---

resource "tls_private_key" "client" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_cert_request" "client" {
  private_key_pem = tls_private_key.client.private_key_pem

  subject {
    common_name  = var.client_common_name
    organization = "Checkout.com"
  }
}

resource "tls_locally_signed_cert" "client" {
  cert_request_pem   = tls_cert_request.client.cert_request_pem
  ca_private_key_pem = tls_private_key.ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.ca.cert_pem

  validity_period_hours = var.client_validity_hours

  allowed_uses = [
    "digital_signature",
    "key_encipherment",
    "client_auth",
  ]
}

# --- Store in Key Vault ---
# Using secrets (not certificates) because we're storing PEM content
# generated by the tls provider, not importing PFX bundles.

resource "azurerm_key_vault_secret" "ca_cert" {
  name            = "ca-certificate"
  value           = tls_self_signed_cert.ca.cert_pem
  key_vault_id    = var.key_vault_id
  content_type    = "application/x-pem-file"
  expiration_date = tls_self_signed_cert.ca.validity_end_time
}

resource "azurerm_key_vault_secret" "ca_key" {
  name            = "ca-private-key"
  value           = tls_private_key.ca.private_key_pem
  key_vault_id    = var.key_vault_id
  content_type    = "application/x-pem-file"
  expiration_date = tls_self_signed_cert.ca.validity_end_time
}

resource "azurerm_key_vault_secret" "client_cert" {
  name            = "client-certificate"
  value           = tls_locally_signed_cert.client.cert_pem
  key_vault_id    = var.key_vault_id
  content_type    = "application/x-pem-file"
  expiration_date = tls_locally_signed_cert.client.validity_end_time
}

resource "azurerm_key_vault_secret" "client_key" {
  name            = "client-private-key"
  value           = tls_private_key.client.private_key_pem
  key_vault_id    = var.key_vault_id
  content_type    = "application/x-pem-file"
  expiration_date = tls_locally_signed_cert.client.validity_end_time
}
