version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosec
    - gocyclo
    - revive
    - misspell
    - unconvert
    - unparam
    - bodyclose

  settings:
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: exported
          disabled: false

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
